packages:
  - docs

overrides:
  rolldown: 'catalog:prod'
  vite: 'catalog:docs'

catalogs:
  dev:
    '@arethetypeswrong/core': ^0.18.2
    '@sxzz/eslint-config': ^7.1.2
    '@sxzz/prettier-config': ^2.2.3
    '@sxzz/test-utils': ^0.5.9
    '@types/debug': ^4.1.12
    '@types/node': ^24.2.1
    '@types/semver': ^7.7.0
    bumpp: ^10.2.3
    eslint: ^9.33.0
    lightningcss: ^1.30.1
    pkg-types: ^2.2.0
    prettier: ^3.6.2
    publint: ^0.3.12
    tsx: ^4.20.3
    typescript: ~5.9.2
    unplugin-lightningcss: ^0.4.1
    unplugin-unused: ^0.5.1
    vitest: ^3.2.4

  docs:
    '@unocss/eslint-plugin': ^66.4.2
    '@vueuse/core': ^13.6.0
    oxc-minify: ^0.82.0
    typedoc: ^0.28.10
    typedoc-plugin-markdown: ^4.8.1
    typedoc-vitepress-theme: ^1.1.2
    unocss: ^66.4.2
    vite: npm:rolldown-vite@latest
    vitepress: ^2.0.0-alpha.7
    vitepress-plugin-group-icons: ^1.6.2
    vitepress-plugin-llms: ^1.7.2
    vue: ^3.5.18
    vue-tsc: ^3.0.5

  prod:
    ansis: ^4.1.0
    cac: ^6.7.14
    chokidar: ^4.0.3
    debug: ^4.4.1
    diff: ^8.0.2
    empathic: ^2.0.0
    hookable: ^5.5.3
    rolldown: latest
    rolldown-plugin-dts: ^0.15.6
    semver: ^7.7.2
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.14
    tree-kill: ^1.2.2
    unconfig: ^7.3.2

ignoredBuiltDependencies:
  - rolldown
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
