packages:
  - docs

overrides:
  rolldown: 'catalog:prod'
  vite: 'catalog:docs'

catalogs:
  dev:
    '@arethetypeswrong/core': ^0.18.2
    '@sxzz/eslint-config': ^7.1.4
    '@sxzz/prettier-config': ^2.2.4
    '@sxzz/test-utils': ^0.5.10
    '@types/debug': ^4.1.12
    '@types/node': ^24.3.1
    '@types/semver': ^7.7.1
    bumpp: ^10.2.3
    eslint: ^9.35.0
    lightningcss: ^1.30.1
    pkg-types: ^2.3.0
    prettier: ^3.6.2
    publint: ^0.3.12
    tsx: ^4.20.5
    typescript: ~5.9.2
    unplugin-lightningcss: ^0.4.2
    unplugin-unused: ^0.5.2
    vitest: ^3.2.4

  docs:
    '@unocss/eslint-plugin': ^66.5.1
    '@vueuse/core': ^13.9.0
    oxc-minify: ^0.87.0
    typedoc: ^0.28.12
    typedoc-plugin-markdown: ^4.8.1
    typedoc-vitepress-theme: ^1.1.2
    unocss: ^66.5.1
    vite: npm:rolldown-vite@latest
    vitepress: ^2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.3
    vitepress-plugin-llms: ^1.7.4
    vue: ^3.5.21
    vue-tsc: ^3.0.6

  prod:
    ansis: ^4.1.0
    cac: ^6.7.14
    chokidar: ^4.0.3
    debug: ^4.4.1
    diff: ^8.0.2
    empathic: ^2.0.0
    hookable: ^5.5.3
    rolldown: latest
    rolldown-plugin-dts: ^0.16.1
    semver: ^7.7.2
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.15
    tree-kill: ^1.2.2
    unconfig: ^7.3.3

ignoredBuiltDependencies:
  - rolldown
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
